config/routes.rb
Expenser::Application.routes.draw do
  resources :expenses

end

app/models/expense.rb
include GeoKit::Geocoders

class Expense < ActiveRecord::Base
  attr_writer :tag_names
  attr_accessible :id, :description, :amount, :location, :tag_names

  has_many :tags, :through => :taggings
  has_many :taggings, :dependent => :destroy

  validates :location, :presence => true
  validates :description, :presence => true
  validates :amount, :presence => true

  #This method is not called even with <%= Expense.tag_names %>
  def tag_names  
    tags.map(&:name).join(' ')  
  end

  before_save :geocode
  after_save :save_tags
    
private

  def geocode
     coordinates = GoogleGeocoder.geocode(self.location)
     self.latitude = coordinates.lat
     self.longitude = coordinates.lng
  end 

  def save_tags
     if @tag_names  
       self.tags = @tag_names.split(' ').map do |name|  
         Tag.find_or_create_by_name(name)  
       end  
     end 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

  # GET /expenses
  # GET /expenses.xml
  def index
    @title = "All Expenses"
    @expenses = Expense.all.reverse
    
    #Calculate Total amount of expenses
    @total = 0.0
    @expenses.each do |e|
      @total += e.amount
    end

    #Return response
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @expenses }
    end

  end

  # GET /expenses/1
  # GET /expenses/1.xml
  def show
    @title = "Show"
    @expense = Expense.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @expense }
    end
  end

  # GET /expenses/new
  # GET /expenses/new.xml
  def new
    @title = "New"
    @expense = Expense.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @expense }
    end
  end

  # GET /expenses/1/edit
  def edit
    @title = "Edit"
    @expense = Expense.find(params[:id])
  end

  # POST /expenses
  # POST /expenses.xml
  def create
    @expense = Expense.new(params[:expense])

    respond_to do |format|
      if @expense.save
        format.html { redirect_to(@expense, :notice => 'Expense was successfully created.') }
        format.xml  { render :xml => @expense, :status => :created, :location => @expense }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @expense.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /expenses/1
  # PUT /expenses/1.xml
  def update
    @expense = Expense.find(params[:id])

    respond_to do |format|
      if @expense.update_attributes(params[:expense])
        format.html { redirect_to(@expense, :notice => 'Expense was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @expense.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.xml
  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to(expenses_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Expenser"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :tag_names, "Tags" %><br />
    <%= f.text_field :tag_names %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<h1>All Expenses</h1>

<!--<table>
  <tr>
    <th>Description</th>
    <th>Location</th>
    <th>Amount</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Tags</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @expenses.each do |expense| %>
  <tr>
    <td><%= expense.description %></td>
    <td><%= expense.location %></td>
    <td><%= expense.amount %></td>
    <td><%= expense.latitude %></td>
    <td><%= expense.longitude %></td>
    <td><%= expense.tags %></td>
    <td><%= link_to 'Show', expense %></td>
    <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
    <td><%= link_to 'Destroy', expense, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table> -->

<% @expenses.each do |e| %>
  <div class="expense-entry">
    <h1><%= e.description %></h1>
    <p><%= e.location %><h2><%= e.amount %></h2></p>
    <p>
       <%= e.tag_names %>
    </p>
  </div>
<% end %>

<br />
<h1>Total Amount: <%= @total %></h1>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @expense.id %>
</p>

<p>
  <b>Description:</b>
  <%= @expense.description %>
</p>

<p>
  <b>Amount:</b>
  <%= @expense.amount %>
</p>

<p>
  <b>Latitude:</b>
  <%= @expense.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @expense.longitude %>
</p>

<p>
  <b>Tags:</b>
  <%= @expense.tag_names %>
</p>


<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>